"""modelo inicial

Revision ID: 2ba6ae9b5456
Revises: 
Create Date: 2026-07-26 20:12:15.864824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba6ae9b5456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('em_execucao', 'encerrado', 'cancelado')", name='ck_projeto_status_valido'),
    sa.CheckConstraint('valor_total >= 0', name='ck_projeto_valor_total_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('alocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=10), nullable=False),
    sa.Column('valor_alocado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("categoria IN ('custeio', 'capital')", name='ck_alocacao_categoria_valida'),
    sa.CheckConstraint('valor_alocado >= 0', name='ck_alocacao_valor_positivo'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fornecedor', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('lancada', 'estornada')", name='ck_despesa_status_valido'),
    sa.CheckConstraint('valor >= 0', name='ck_despesa_valor_positivo'),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprovante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('despesa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprovante')
    op.drop_table('despesa')
    op.drop_table('alocacao')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('projeto')
    # ### end Alembic commands ###
