"""adiciona tipo_despesa

Revision ID: 714d05335617
Revises: 2ba6ae9b5456
Create Date: 2026-07-28 16:45:50.663727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714d05335617'
down_revision = '2ba6ae9b5456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('alocacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_despesa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipo_despesa', ['tipo_despesa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alocacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_despesa_id')

    op.drop_table('tipo_despesa')
    # ### end Alembic commands ###
